version: '3.8'
services:
  db:
    build:
      context: ./db  # Points to the db directory where the Dockerfile is
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  node-service:
    build:
      context: ./api  # Points to the api directory where the Dockerfile is
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx  # Points to the nginx directory where the Dockerfile is
    ports:
      - "8080:80"
    depends_on:
      - node-service

volumes:
  db-data:
